[package]
name = "sendit"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
block2 = "0.6"
clap = { version = "4.6.7", features = ["derive"] }
hex = "0.4.3"
libc = "0.2.189"
objc2 = { version = "0.6", features = ["exception"] }
objc2-foundation = "0.3"
objc2-virtualization = "0.3"
serde = { version = "1.0.229", features = ["derive"] }
sha2 = "0.11.0"
toml = "1.1.6"
uuid = { version = "1.26.1", features = ["v5"] }
