//! Turning the configured mounts into virtiofs shares, plus the manifest that
//! tells the guest where to mount them and which time zone to use.
//!
//! Every VM gets a read-only `sendit-meta` share holding the manifest, the
//! script that applies it (`assets/sendit-mounts.sh`) and the login message.
//! The base image only knows to mount that share and run the script, so the
//! mount logic, the time zone and the message can change without
//! re-provisioning.
//!
//! Hiding `.git` keeps it out of reach of the guest user, which has no root
//! rights to unmount the mask. Only the host can become root in the guest
//! (`sendit ssh --root`).

use std::fmt::Write;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::config::VmSettings;

pub const META_TAG: &str = "sendit-meta";
const MOUNT_SCRIPT: &str = include_str!("assets/sendit-mounts.sh");
const BANNER: &str = include_str!("assets/banner.txt");

/// The login message below the banner.
const MOTD: &str = "  Light and fast VMs. Your project is in your home directory.
  Logging out of the console (exit or Ctrl-D) shuts the VM down.
  There is no sudo here; for root, run `sendit ssh --root` on the host.

";

/// A host directory exposed to the guest under a virtiofs tag.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Share {
    pub tag: String,
    pub host: PathBuf,
    pub read_only: bool,
}

/// Writes the manifest, mount script and login message into `meta_dir` and
/// returns all shares for the VM, the meta share first.
pub fn prepare(settings: &VmSettings, meta_dir: &Path) -> Result<Vec<Share>> {
    fs::create_dir_all(meta_dir).with_context(|| format!("creating {}", meta_dir.display()))?;
    fs::write(
        meta_dir.join("mounts"),
        manifest(settings, host_timezone().as_deref()),
    )?;
    fs::write(meta_dir.join("mount.sh"), MOUNT_SCRIPT)?;
    fs::write(meta_dir.join("motd"), motd(settings))?;
    Ok(shares(settings, meta_dir))
}

/// The virtiofs tag of `settings.mounts[i]`.
fn tag(i: usize) -> String {
    match i {
        0 => "project".into(),
        _ => format!("m{}", i - 1),
    }
}

fn shares(settings: &VmSettings, meta_dir: &Path) -> Vec<Share> {
    let meta = Share {
        tag: META_TAG.into(),
        host: meta_dir.to_path_buf(),
        read_only: true,
    };
    let mounts = settings.mounts.iter().enumerate().map(|(i, mount)| Share {
        tag: tag(i),
        host: mount.host.clone(),
        read_only: mount.read_only,
    });
    std::iter::once(meta).chain(mounts).collect()
}

/// The host's time zone as an IANA name such as `Europe/Berlin`, read from
/// the /etc/localtime symlink that macOS keeps pointing at the zone set in
/// System Settings. None if it can't be told, which leaves the guest on UTC.
fn host_timezone() -> Option<String> {
    timezone_name(&fs::read_link("/etc/localtime").ok()?)
}

/// The zone name in a link target such as
/// `/var/db/timezone/zoneinfo/Europe/Berlin`, if it looks like one: the guest
/// looks it up below /usr/share/zoneinfo as root.
fn timezone_name(target: &Path) -> Option<String> {
    let target = target.to_str()?;
    let (_, name) = target.rsplit_once("/zoneinfo/")?;
    let valid = !name.is_empty()
        && name.split('/').all(|part| {
            !part.is_empty()
                && !part.starts_with('.')
                && part
                    .chars()
                    .all(|c| c.is_ascii_alphanumeric() || "_+-.".contains(c))
        });
    valid.then(|| name.to_string())
}

/// One line per action, applied in order:
/// `share <tag> <ro|rw> <guest path>`, `hide <guest path>`,
/// `workdir <guest path>` and `timezone <name>`. `Config::resolve` has made
/// sure the guest paths fit on a line.
fn manifest(settings: &VmSettings, timezone: Option<&str>) -> String {
    let mut text = String::from("# Generated by sendit; applied by mount.sh on boot.\n");
    for (i, mount) in settings.mounts.iter().enumerate() {
        let _ = writeln!(
            text,
            "share {} {} {}",
            tag(i),
            mount.mode(),
            mount.guest.display()
        );
    }
    let project = &settings.project().guest;
    if !settings.expose_git {
        let _ = writeln!(text, "hide {}", project.join(".git").display());
    }
    let _ = writeln!(text, "workdir {}", project.display());
    if let Some(timezone) = timezone {
        let _ = writeln!(text, "timezone {timezone}");
    }
    text
}

/// The login message, which mount.sh installs as /etc/motd: the banner in
/// orange, unless turned off, then `MOTD`.
fn motd(settings: &VmSettings) -> String {
    if settings.banner {
        format!("\x1b[1;38;5;208m{BANNER}\x1b[0m{MOTD}")
    } else {
        // Apart from the kernel line the login shows before it.
        format!("\n{MOTD}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{ByteSize, GUEST_USER, Mount};

    fn settings(expose_git: bool) -> VmSettings {
        let mount = |host: &str, guest: &str, read_only| Mount {
            host: host.into(),
            guest: guest.into(),
            read_only,
        };
        VmSettings {
            cpus: 1,
            memory: ByteSize::gib(1),
            disk_size: ByteSize::gib(8),
            mounts: vec![
                mount("/p", "/home/dev/p", false),
                mount("/data", "/mnt/my data", true),
                mount("/cache", "/home/dev/.cache", false),
            ],
            expose_git,
            banner: true,
            image: None,
        }
    }

    #[test]
    fn builds_shares_and_manifest() {
        let settings = settings(false);
        let shares = shares(&settings, Path::new("/vm/run/meta"));
        let tags: Vec<_> = shares.iter().map(|s| s.tag.as_str()).collect();
        assert_eq!(tags, ["sendit-meta", "project", "m0", "m1"]);
        assert!(shares[0].read_only);
        assert_eq!(shares[2].host, Path::new("/data"));
        assert!(shares[2].read_only);

        assert_eq!(
            manifest(&settings, Some("Europe/Berlin")),
            "# Generated by sendit; applied by mount.sh on boot.\n\
             share project rw /home/dev/p\n\
             share m0 ro /mnt/my data\n\
             share m1 rw /home/dev/.cache\n\
             hide /home/dev/p/.git\n\
             workdir /home/dev/p\n\
             timezone Europe/Berlin\n"
        );
        assert!(!manifest(&settings, None).contains("timezone"));
    }

    #[test]
    fn reads_the_timezone_from_the_link_target() {
        let name = |target: &str| timezone_name(Path::new(target));
        assert_eq!(
            name("/var/db/timezone/zoneinfo/Europe/Berlin").as_deref(),
            Some("Europe/Berlin")
        );
        assert_eq!(
            name("/usr/share/zoneinfo/America/Argentina/Buenos_Aires").as_deref(),
            Some("America/Argentina/Buenos_Aires")
        );
        assert_eq!(
            name("/var/db/timezone/zoneinfo/Etc/GMT+1").as_deref(),
            Some("Etc/GMT+1")
        );
        assert_eq!(
            name("/var/db/timezone/zoneinfo/UTC").as_deref(),
            Some("UTC")
        );
        assert_eq!(name("/var/db/timezone/zoneinfo/../../../etc/shadow"), None);
        assert_eq!(name("/var/db/timezone/zoneinfo/Europe/"), None);
        assert_eq!(name("/var/db/timezone/zoneinfo/Europe/Ber lin"), None);
        assert_eq!(name("/etc/localtime.bak"), None);
    }

    #[test]
    fn leaves_out_the_banner_on_request() {
        let mut settings = settings(false);
        assert!(motd(&settings).contains(BANNER));
        settings.banner = false;
        assert!(!motd(&settings).contains(BANNER));
        assert!(motd(&settings).ends_with(MOTD));
    }

    #[test]
    fn exposes_git_on_request() {
        assert!(!manifest(&settings(true), None).contains("hide"));
    }

    #[test]
    fn script_understands_the_manifest() {
        assert!(MOUNT_SCRIPT.contains("share)"));
        assert!(MOUNT_SCRIPT.contains("hide)"));
        assert!(MOUNT_SCRIPT.contains("workdir)"));
        assert!(MOUNT_SCRIPT.contains("timezone)"));
        assert!(MOUNT_SCRIPT.contains(&format!("\nuser={GUEST_USER}\n")));
    }
}
