//! Turning the configured mounts into virtiofs shares, plus the manifest that
//! tells the guest where to mount them.
//!
//! Every VM gets a read-only `sendit-meta` share holding the manifest and the
//! script that applies it (`assets/sendit-mounts.sh`). The base image only
//! knows to mount that share and run the script, so the mount logic can
//! change without re-provisioning.
//!
//! Hiding `.git` keeps it out of sight of the guest user, but it is not a
//! security boundary: root in the guest can unmount the mask.

use std::fmt::Write;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, ensure};

use crate::config::VmSettings;

pub const META_TAG: &str = "sendit-meta";
const MOUNT_SCRIPT: &str = include_str!("assets/sendit-mounts.sh");

/// A host directory exposed to the guest under a virtiofs tag.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Share {
    pub tag: String,
    pub host: PathBuf,
    pub read_only: bool,
}

/// Writes the manifest and mount script into `meta_dir` and returns all
/// shares for the VM, the meta share first.
pub fn prepare(settings: &VmSettings, meta_dir: &Path) -> Result<Vec<Share>> {
    fs::create_dir_all(meta_dir).with_context(|| format!("creating {}", meta_dir.display()))?;
    let shares = shares(settings, meta_dir);
    fs::write(meta_dir.join("mounts"), manifest(settings, &shares[1..])?)?;
    fs::write(meta_dir.join("mount.sh"), MOUNT_SCRIPT)?;
    Ok(shares)
}

fn shares(settings: &VmSettings, meta_dir: &Path) -> Vec<Share> {
    let meta = Share {
        tag: META_TAG.into(),
        host: meta_dir.to_path_buf(),
        read_only: true,
    };
    // The project is always the first mount (see `Config::resolve`).
    let mounts = settings.mounts.iter().enumerate().map(|(i, mount)| Share {
        tag: if i == 0 { "project".into() } else { format!("m{}", i - 1) },
        host: mount.host.clone(),
        read_only: mount.read_only,
    });
    std::iter::once(meta).chain(mounts).collect()
}

/// One line per action, applied in order:
/// `share <tag> <ro|rw> <guest path>`, `hide <guest path>` and
/// `workdir <guest path>`.
fn manifest(settings: &VmSettings, shares: &[Share]) -> Result<String> {
    let mut text = String::from("# Generated by sendit; applied by mount.sh on boot.\n");
    for (share, mount) in shares.iter().zip(&settings.mounts) {
        let guest = guest_path(&mount.guest)?;
        let mode = if share.read_only { "ro" } else { "rw" };
        writeln!(text, "share {} {mode} {guest}", share.tag)?;
    }
    // The project is always the first mount (see `Config::resolve`).
    let project = &settings.mounts[0].guest;
    if !settings.expose_git {
        writeln!(text, "hide {}", guest_path(&project.join(".git"))?)?;
    }
    writeln!(text, "workdir {}", guest_path(project)?)?;
    Ok(text)
}

fn guest_path(path: &Path) -> Result<&str> {
    let s = path
        .to_str()
        .with_context(|| format!("guest path {} is not valid UTF-8", path.display()))?;
    ensure!(
        !s.contains(|c: char| c.is_control()) && s.trim() == s,
        "guest path {s:?} may not contain control characters or surrounding spaces"
    );
    Ok(s)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{ByteSize, Mount};

    fn settings(expose_git: bool) -> VmSettings {
        let mount = |host: &str, guest: &str, read_only| Mount {
            host: host.into(),
            guest: guest.into(),
            read_only,
        };
        VmSettings {
            cpus: 1,
            memory: ByteSize::gib(1),
            disk_size: ByteSize::gib(8),
            mounts: vec![
                mount("/p", "/home/dev/p", false),
                mount("/data", "/mnt/my data", true),
                mount("/cache", "/home/dev/.cache", false),
            ],
            expose_git,
        }
    }

    #[test]
    fn builds_shares_and_manifest() {
        let settings = settings(false);
        let shares = shares(&settings, Path::new("/vm/run/meta"));
        let tags: Vec<_> = shares.iter().map(|s| s.tag.as_str()).collect();
        assert_eq!(tags, ["sendit-meta", "project", "m0", "m1"]);
        assert!(shares[0].read_only);
        assert_eq!(shares[2].host, Path::new("/data"));
        assert!(shares[2].read_only);

        assert_eq!(
            manifest(&settings, &shares[1..]).unwrap(),
            "# Generated by sendit; applied by mount.sh on boot.\n\
             share project rw /home/dev/p\n\
             share m0 ro /mnt/my data\n\
             share m1 rw /home/dev/.cache\n\
             hide /home/dev/p/.git\n\
             workdir /home/dev/p\n"
        );
    }

    #[test]
    fn exposes_git_on_request() {
        let settings = settings(true);
        let shares = shares(&settings, Path::new("/meta"));
        assert!(!manifest(&settings, &shares[1..]).unwrap().contains("hide"));
    }

    #[test]
    fn rejects_unsafe_guest_paths() {
        let mut settings = settings(true);
        settings.mounts[1].guest = "/mnt/a\nhide /".into();
        let shares = shares(&settings, Path::new("/meta"));
        assert!(manifest(&settings, &shares[1..]).is_err());
    }

    #[test]
    fn script_understands_the_manifest() {
        assert!(MOUNT_SCRIPT.contains("share)"));
        assert!(MOUNT_SCRIPT.contains("hide)"));
        assert!(MOUNT_SCRIPT.contains("workdir)"));
    }
}
